name: Refresh RSS
on:
  schedule:
    - cron:  '0 */2 * * *'           # every two hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  refresh-rss:
    runs-on: ubuntu-latest
    concurrency: refresh-rss
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dir: .uv/cache

      - run: uv sync
      - run: uv run python main.py


      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/* data/* uv.lock || true
          if [[ -n $(git status --porcelain) ]]; then
            git commit -m "auto-update $(date -u +'%F %T')"
            git push
          fi

    #   # 🔔  Open an issue if *any* prior step failed
    #   - name: Create issue on failure
    #     if: failure()
    #     uses: peter-evans/create-issue-from-file@v4
    #     with:
    #       title: "Scraper failed – run ${{ github.run_id }}"
    #       content-filepath: <(echo "See logs: ${{ github.run_url }}")
    #       labels: bot, failure
